server:
  port: 8080

cache:
  fixedRateValue: 3600000

spring:
  datasource:
    url: jdbc:postgresql://${DEV_GIGA_HOST}:${DEV_LOCAL_PORT}/${DEV_GIGA_DB_NAME}
    username: ${DEV_GIGA_LOGIN}
    password: ${DEV_GIGA_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${DEV_GIGA_HOST}:9092
    groups:
      chat-info: gigachat-info-group
      request-data: gigachat-request-group

  output:
    ansi:
      enabled: ALWAYS

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


